### ISSUE TITLE
[Suggestion] Add the Turbo emotes / "Twitch" subscriber emotes

### ISSUE THREAD

**Issue by flarn2006** [graulund/secretdungeonemotes#1]
That way, people with this addon installed will see them even if the person posting them isn't a subscriber. It's not like it will take away revenue from Twitch (not that I think they could sue you for it or anything :smile:) because most Twitch users still won't have it installed.

**Comment by walle303** [comment]
Wow flarn2006 OneHand

**Comment by flarn2006** [comment]
Now you're stalking me on Github too? ![](http://static-cdn.jtvnw.net/emoticons/v1/25/1.0)

**Comment by walle303** [comment]
Nope, just a coincidence i saw this 'issue' ![EleGiggle](http://static-cdn.jtvnw.net/emoticons/v1/4339/1.0)

**Comment by PikalaxALT** [comment]
walle303... TriHard

**Comment by walle303** [comment]
![DansGame](http://static-cdn.jtvnw.net/emoticons/v1/33/1.0)

**Comment by MapperTV** [comment]
![MingLee](https://static-cdn.jtvnw.net/emoticons/v1/68856/1.0)

**Comment by graulund** [comment]
Yeah, sorry, I won't add these.
