### ISSUE TITLE
I don't get how when FFZ is disabled it doesn't work..

### ISSUE THREAD

**Issue by SynaDesigns** [graulund/secretdungeonemotes#4]
So i've see your public version and when i try to use your its still only works with FFZ but most of the people that use yours don't have this problem. Is there something i have to reset on my chrome or?

EDIT: Also does it on Firefox.

**Comment by SynaDesigns** [comment]
Nothing?

**Comment by walle303** [comment]
It works fine without FFZ
If you have BTTV installed that will mess it up

**Comment by SynaDesigns** [comment]
That should be fixed then. Cause most of twitch uses BTTV and if it can't have them both not many people would like to use it as so many people love BTTV it will be hard to just let it "go"

**Comment by walle303** [comment]
Thats not an issue with FFZ/SDE Thats an issue with how BTTV Hijacks the chat system with its own system. Other addons like the TPP Chat Filter also are broken by BTTV.

**Comment by SynaDesigns** [comment]
Well.. still the point BTTV should then fix it.. Cause they know mainly all of twitch uses it and if they wanted to use SDE they would have to disable an addon that they prob love.

**Comment by walle303** [comment]
BTTV won't fix it as there entire program is written around their chat handler, they just will say that SDE should add support for their chat handler. Its also possible you can convince groulund/electricnet to add BTTV chat handler support.
For now just continue using it with FFZ (or disable BTTV)
